token implementation fixes
sup25/store pull request #24
Opened 2024-04-03 07:42 UTC by sup25

- Implemented the blacklist functionality correctly by generating both the accessToken and refreshToken, followed by querying the database to verify the blacklist status of the token.
- Verified the token blacklist status by querying the database immediately after token generation to ensure proper handling of blacklisted tokens.

Reviewer 
@Elnatanv

2024-04-04 09:54 UTC, Elnatanv requested changes

2024-04-04 09:54 UTC, Elnatanv commented on app/api/v1/user/auth/refreshToken/route.js
> +    try {
@sup25 This should be a service: invalidateUserTokens . pass the token as argument.  await invalidateUserTokens(refreshToken)

2024-04-04 09:54 UTC, Elnatanv commented on app/api/v1/user/auth/tokenService/generateTokens/index.js
> +      type: "ACCESS_TOKEN ",
you have a space after ACCESS_TOKEN

2024-04-04 09:54 UTC, Elnatanv commented on app/api/v1/user/auth/tokenService/generateTokens/index.js
> +  await prisma.token.updateMany({
this is the same service as invalidateUserTokens . but you dont need to do it inside this service. its a business logic. we should do invalidate on a controller level, then to generate.

2024-04-04 09:54 UTC, Elnatanv commented on app/api/v1/user/auth/tokenService/generateTokens/index.js
> +  const expDate = new Date(decodedRefreshToken.exp * 1000).toISOString();
should be a util function - takes decodedRefreshToken.exp as argument. reutrns the date.

2024-04-04 09:54 UTC, Elnatanv commented on app/api/v1/user/auth/tokenService/verifyToken/index.js
> +    const blacklistedToken = await prisma.token.findFirst({
create a service check if black listed. put the logic there. and call it inside auth wrapper function. before verifying the token, means if token is black listed (or not exist) - we want to return error 401 . and exist. inside where:{} remove id. we dont care about the id.

2024-04-04 10:07 UTC, Elnatanv requested changes

2024-04-04 10:07 UTC, Elnatanv commented on app/api/v1/user/auth/refreshToken/route.js
>    try {
All this try catch should be a controller. refreshToken controller

2024-04-12 03:54 UTC, sup25 commented on app/api/v1/user/auth/refreshToken/route.js
> +    try {
Done

2024-04-12 03:54 UTC, sup25 commented on app/api/v1/user/auth/tokenService/generateTokens/index.js
> +      type: "ACCESS_TOKEN ",
Done

2024-04-12 03:56 UTC, sup25 commented on app/api/v1/user/auth/tokenService/generateTokens/index.js
> +  const expDate = new Date(decodedRefreshToken.exp * 1000).toISOString();
Done

2024-04-12 03:56 UTC, sup25 commented on app/api/v1/user/auth/tokenService/generateTokens/index.js
> +  await prisma.token.updateMany({
Done

2024-04-12 03:57 UTC, sup25 commented on app/api/v1/user/auth/tokenService/verifyToken/index.js
> +    const blacklistedToken = await prisma.token.findFirst({
Need to review

2024-04-12 03:57 UTC, sup25 commented on app/api/v1/user/auth/refreshToken/route.js
>    try {
Done

2024-05-13 07:52 UTC, merged